apiVersion: v1
kind: Pod
metadata:
  name: lab4-<name>-pod 	
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html  
          name: my-storage                   	
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: lab4-volume-<name>-pvc