apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab4-volume-<name>-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: <name>-sc
