apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab4-volume-sivaroot-pvc	# lab4-volume-<name>-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "sivaroot-storage"  # <name>-sc



