apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sivaroot-storage
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS          # หรือ Premium_LRS, StandardSSD_LRS
  kind: Managed                  # ใช้ Managed Disk ของ Azure
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete