apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <name>-sc
provisioner: disk.csi.azure.com
parameters:
  skuName: StandardSSD_ZRS 	
  kind: Managed                  			# ใช้ Managed Disk ของ Azure
volumeBindingMode: WaitForFirstConsumer  	# Immediate,WaitForFirstConsumer
reclaimPolicy: Delete            			# Retail, Delete

