apiVersion: v1
kind: Pod
metadata:
  name: volume-<name>-lab2
spec:
  containers:
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP

    - name: content-agent
      image: sivaroot/content-agent:latest
      volumeMounts:
        - name: content
          mountPath: /var/webtime
  volumes:
    - name: content
      hostPath:
        path: /tmp/kubehomecoming
        type: DirectoryOrCreate