apiVersion: v1
kind: Pod
metadata:
  name: lab3-homecomming-pod
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html 
          name: my-storage                   	
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: volume-homecomming-pvc 
