apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-homecomming-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: "/subscriptions/bd45165d-feae-4e6d-af5d-4ee6e4f3b835/resourceGroups/MC_kube-homecoming_kube-homecoming-cluster_southeastasia/providers/Microsoft.Compute/disks/homecoming_disk"
    volumeAttributes:
      fsType: ext4