apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-homecomming-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: volume-homecomming-pv
  storageClassName: “managed-csi”



